name: chat_app
description: A Flutter chat application with gRPC.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  file_picker: ^6.1.1
  fixnum: ^1.1.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.7
  grpc: ^3.2.4
  image_picker: ^1.0.7
  intl: ^0.19.0
  protobuf: ^3.1.0
  url_launcher: ^6.2.5
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - amplifyconfiguration.json
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700 